name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'backend/**'
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Copy Docker files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "backend/,docker-compose.yml,docker-compose.dev.yml"
        target: "/var/www/WiA11y/"
        
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Install Docker if not present
          if ! command -v docker &> /dev/null; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
          fi
          
          # Install Docker Compose if not present
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
          
          cd /var/www/WiA11y
          
          # Explicitly use production compose file
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml build --no-cache app
          
          # Start with production environment variables
          MONGODB_URI="${{ secrets.MONGODB_URI }}" \
          JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          CORS_ORIGIN="https://wia11y.netlify.app" \
          SMTP_HOST="${{ secrets.SMTP_HOST }}" \
          SMTP_PORT="${{ secrets.SMTP_PORT }}" \
          SMTP_USER="${{ secrets.SMTP_USER }}" \
          SMTP_PASS="${{ secrets.SMTP_PASS }}" \
          SMTP_FROM="${{ secrets.SMTP_FROM }}" \
          FRONTEND_URL="https://wia11y.netlify.app" \
          docker-compose -f docker-compose.yml up -d
          
          # Prune old images
          docker image prune -f 