name: Deploy Backend

on:
  push:
    branches: [ primary ]
    paths:
      - '.github/workflows/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/WiA11y/backend
          git pull
          npm install
          # Verify routes are registered
          echo "Checking registered routes..."
          node -e "const app = require('./src/app.js'); console.log('Registered routes:', app._router.stack.filter(r => r.route).map(r => r.route.path))"
          # Delete existing process if it exists
          pm2 delete wia11y || true
          # Start with production environment
          NODE_ENV=production \
          MONGODB_URI="${{ secrets.MONGODB_URI }}" \
          JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          CORS_ORIGIN="https://wia11y.netlify.app" \
          SMTP_HOST="${{ secrets.SMTP_HOST }}" \
          SMTP_PORT="${{ secrets.SMTP_PORT }}" \
          SMTP_USER="${{ secrets.SMTP_USER }}" \
          SMTP_PASS="${{ secrets.SMTP_PASS }}" \
          SMTP_FROM="${{ secrets.SMTP_FROM }}" \
          FRONTEND_URL="https://wia11y.netlify.app" \
          pm2 start src/server.js \
            --name "wia11y" \
            --time \
            --no-autorestart \
            --exp-backoff-restart-delay=100
          pm2 save 

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgbm1 \
          libasound2 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgdk-pixbuf2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libxss1 \
          xdg-utils \
          libu2f-udev \
          libvulkan1 \
          xvfb

    - name: Setup Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb 