name: Deploy Backend

on:
  push:
    branches: [ primary ]
    paths:
      - '.github/workflows/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/WiA11y/backend
          git pull
          npm install
          pm2 delete wia11y || true
          NODE_ENV=production \
          MONGODB_URI="mongodb+srv://wia11y_admin:ZZyTkJrL34javvag@wia11y.wpyxo.mongodb.net/?retryWrites=true&w=majority&appName=WiA11y" \
          JWT_SECRET="p2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdS" \
          CORS_ORIGIN="https://wia11y.netlify.app" \
          pm2 start src/server.js \
            --name "wia11y" \
            --time \
            --no-autorestart \
            --exp-backoff-restart-delay=100
          pm2 save 