name: Deploy Backend

on:
  push:
    branches: [ primary ]
    paths:
      - '.github/workflows/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Install Redis if not already installed
          if ! command -v redis-cli &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y redis-server
            sudo systemctl enable redis-server
            sudo systemctl start redis-server
          fi
          
          cd /var/www/WiA11y/backend
          git pull
          npm install
          
          # Start with production environment
          NODE_ENV=production \
          MONGODB_URI="${{ secrets.MONGODB_URI }}" \
          JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          CORS_ORIGIN="https://wia11y.netlify.app" \
          SMTP_HOST="${{ secrets.SMTP_HOST }}" \
          SMTP_PORT="${{ secrets.SMTP_PORT }}" \
          SMTP_USER="${{ secrets.SMTP_USER }}" \
          SMTP_PASS="${{ secrets.SMTP_PASS }}" \
          SMTP_FROM="${{ secrets.SMTP_FROM }}" \
          FRONTEND_URL="https://wia11y.netlify.app" \
          REDIS_URL="redis://localhost:6379" \
          pm2 start src/server.js \
            --name "wia11y" \
            --time \
            --no-autorestart \
            --exp-backoff-restart-delay=100
          pm2 save 