name: Deploy Backend

on:
  push:
    branches: [ primary ]
    paths:
      - '.github/workflows/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/WiA11y/backend
          git pull
          npm install
          pm2 delete wia11y || true
          # Create logs directory if it doesn't exist
          mkdir -p logs
          # Start the application using ecosystem config
          pm2 start ecosystem.config.js
          pm2 save 